ktor {
   deployment {
      port = 8080
      port = ${?PORT}
   }
   application {
      modules = [ com.animatedhandwriting.ApplicationKt.module ]
   }
}

database {
   url = "jdbc:postgresql://localhost:5432/handwriting"
   url = ${?DATABASE_URL}
   user = "postgres"
   user = ${?DATABASE_USER}
   password = ""
   password = ${?DATABASE_PASSWORD}
}
